[package]
name = "dynamodb-toolbox"
version = "0.1.4"
edition = "2024"

[dependencies]
aws-config = { version = "1" }
aws-sdk-dynamodb = { version = "1" }
aws-smithy-types = { version = "1" }
aws-smithy-runtime-api = { version = "1" }
futures = { version = "0.3" }
tokio = { version = "1", features = ["full"] }
tracing = { version = "0.1" }
uuid = { version = "1", features = ["v4", "v8"] }

[dev-dependencies]
tracing-subscriber = { version = "0.3", features = ["tracing"] }
